/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import dao.DaoFactory;
import dao.QuadrinhosDAO;
import dao.UsuarioDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Quadrinhos;
import model.Usuario;

/**
 *
 * @author higor_x
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        cadastroUsuario.setVisible(false);
        cadastroHq.setVisible(false);
       
    }
    
    public void limparCampos(){
        txtNome.setText("");
        txtSenha.setText("");
        txtEmail.setText("");
        txtNascimento.setText("");
        txtCadastro.setText("");
        txtEndereco.setText("");
        txtQuadrinho.setText("");
        txtEditora.setText("");
        txtAno.setText("");
        txtNumero.setText("");
        comboBox.setSelectedIndex(0);
        
        
    }
    int novoId;
    
 SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastroUsuario = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btProcura = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNascimento = new javax.swing.JTextField();
        txtCadastro = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        btCadastro = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        btAtualiza = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        btApaga = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        cadastroHq = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtQuadrinho = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEditora = new javax.swing.JTextField();
        comboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        btHqCad = new javax.swing.JButton();
        btHqUpdate = new javax.swing.JButton();
        btHqDelete = new javax.swing.JButton();
        btHqProcurar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        cadastroUsuario.setBackground(new java.awt.Color(204, 204, 204));
        cadastroUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("Endereço");
        cadastroUsuario.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 294, -1, -1));

        btProcura.setText("Procurar");
        btProcura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProcuraActionPerformed(evt);
            }
        });
        cadastroUsuario.add(btProcura, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 420, -1, -1));
        cadastroUsuario.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 92, 188, -1));
        cadastroUsuario.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 180, 188, -1));
        cadastroUsuario.add(txtNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 223, 188, -1));
        cadastroUsuario.add(txtCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 268, 188, -1));

        jLabel16.setText("Nome Usuario");
        cadastroUsuario.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 75, -1, -1));
        cadastroUsuario.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 314, 188, -1));

        jLabel17.setText("Senha Usuário");
        cadastroUsuario.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 118, -1, -1));
        cadastroUsuario.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 136, 188, -1));

        jLabel18.setText("E-mail");
        cadastroUsuario.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 162, -1, -1));

        btCadastro.setText("Cadastrar");
        btCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroActionPerformed(evt);
            }
        });
        cadastroUsuario.add(btCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 379, -1, -1));

        jLabel19.setText("Data Nascimento");
        cadastroUsuario.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 206, -1, -1));

        btAtualiza.setText("Atualizar");
        btAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizaActionPerformed(evt);
            }
        });
        cadastroUsuario.add(btAtualiza, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 379, -1, -1));

        jLabel20.setText("Data de Cadastro");
        cadastroUsuario.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 249, -1, -1));

        btApaga.setText("Apagar");
        btApaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApagaActionPerformed(evt);
            }
        });
        cadastroUsuario.add(btApaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 420, 81, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Cadastrar Usuário");
        cadastroUsuario.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 11, -1, -1));

        cadastroHq.setBackground(new java.awt.Color(204, 204, 204));
        cadastroHq.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cadastrar Quadrinhos");
        cadastroHq.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel2.setText("Nome do Quadrinho");
        cadastroHq.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txtQuadrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuadrinhoActionPerformed(evt);
            }
        });
        cadastroHq.add(txtQuadrinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 250, -1));

        jLabel3.setText("Editora");
        cadastroHq.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel4.setText("Numero");
        cadastroHq.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));
        cadastroHq.add(txtEditora, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 250, -1));

        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JANEIRO", "FEVEREIRO", "MARÇO", "ABRIL", "MAIO", "JUNHO", "JULHO", "AGOSTO", "SETEMBRO", "OUTUBRO", "NOVEMBRO", "DEZEMBRO" }));
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });
        cadastroHq.add(comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 90, 20));

        jLabel5.setText("Mês");
        cadastroHq.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 10));

        jLabel6.setText("Ano");
        cadastroHq.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        cadastroHq.add(txtAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 50, -1));
        cadastroHq.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 50, -1));

        btHqCad.setText("Cadastrar");
        btHqCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHqCadActionPerformed(evt);
            }
        });
        cadastroHq.add(btHqCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        btHqUpdate.setText("Atualizar");
        cadastroHq.add(btHqUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 80, -1));

        btHqDelete.setText("Apagar");
        btHqDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHqDeleteActionPerformed(evt);
            }
        });
        cadastroHq.add(btHqDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 80, -1));

        btHqProcurar.setText("Procurar");
        cadastroHq.add(btHqProcurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 80, -1));

        jMenu1.setText("File");

        jMenuItem1.setText("Cadastrar Usuário");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Cadastrar Quadrinho");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Cadastrar Livro");
        jMenu1.add(jMenuItem4);
        jMenu1.add(jSeparator1);

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Informações");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                .addComponent(cadastroHq, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastroHq, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        cadastroUsuario.setVisible(true);   
        cadastroHq.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        cadastroUsuario.setVisible(false); 
        cadastroHq.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btApagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApagaActionPerformed
        try{
            UsuarioDAO userDao = DaoFactory.criarUsuario();
            String name = txtNome.getText();
            String senha = txtSenha.getPassword().toString();
            String email = txtEmail.getText();
            Date nascimento = sdf.parse(txtNascimento.getText());
            Date cadastro = sdf.parse(txtCadastro.getText());
            String endereco =   txtEndereco.getText();

            Usuario user = new Usuario(name,senha,email,nascimento,cadastro,endereco);

            userDao.delete(novoId);

            limparCampos();

        }
        catch(ParseException e){
            JOptionPane.showMessageDialog(null, "Erro Formato de Data Inválido forma válida DD/MM/YYYY ");
        } // TODO add your handling code here:
    }//GEN-LAST:event_btApagaActionPerformed

    private void btAtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizaActionPerformed
        try{
            UsuarioDAO userDao = DaoFactory.criarUsuario();
            String name = txtNome.getText();
            String senha = txtSenha.getPassword().toString();
            String email = txtEmail.getText();
            Date nascimento = sdf.parse(txtNascimento.getText());
            Date cadastro = sdf.parse(txtCadastro.getText());
            String endereco =   txtEndereco.getText();

            Usuario user = new Usuario(name,senha,email,nascimento,cadastro,endereco);
            user.setId_usuario(novoId);
            userDao.update(user);

            limparCampos();

        }
        catch(ParseException e){
            JOptionPane.showMessageDialog(null, "Erro Formato de Data Inválido forma válida DD/MM/YYYY ");
        }
    }//GEN-LAST:event_btAtualizaActionPerformed

    private void btCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroActionPerformed

        try{
            UsuarioDAO userDao = DaoFactory.criarUsuario();
            String name = txtNome.getText();
            String senha = txtSenha.getPassword().toString();
            String email = txtEmail.getText();
            Date nascimento = sdf.parse(txtNascimento.getText());
            Date cadastro = sdf.parse(txtCadastro.getText());
            String endereco =   txtEndereco.getText();

            Usuario user = new Usuario(name,senha,email,nascimento,cadastro,endereco);
            userDao.insere(user);

            limparCampos();

        }
        catch(ParseException e){
            JOptionPane.showMessageDialog(null, "Erro Formato de Data Inválido forma válida DD/MM/YYYY ");
        }
    }//GEN-LAST:event_btCadastroActionPerformed

    private void btProcuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProcuraActionPerformed
        String ids = JOptionPane.showInputDialog("Digite o Id do usuário");
        int id = Integer.parseInt(ids);
        novoId = id;
        UsuarioDAO userDao = DaoFactory.criarUsuario();
        Usuario user = userDao.acharPorId(id);
        limparCampos();

        txtNome.setText(user.getNome_usuario());
        txtSenha.setText("");
        txtEmail.setText(user.getEmail_usuario());
        txtNascimento.setText(sdf.format(user.getNascimento()));
        txtCadastro.setText(sdf.format(user.getCadastro()));
        txtEndereco.setText(user.getEndereco());
    }//GEN-LAST:event_btProcuraActionPerformed

    private void txtQuadrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuadrinhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuadrinhoActionPerformed

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
              // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxActionPerformed

    private void btHqCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHqCadActionPerformed
        
        QuadrinhosDAO hqDao = DaoFactory.criarQuadrinho();
        String nome = txtQuadrinho.getText().toUpperCase();
        String editora = txtEditora.getText().toUpperCase();
        int numero = Integer.parseInt(txtNumero.getText());
        String mes = comboBox.getSelectedItem().toString();
        int ano = Integer.parseInt(txtAno.getText());
        
        Quadrinhos hq = new Quadrinhos(nome,editora,numero,mes,ano);
        
        hqDao.insere(hq);
        
            // TODO add your handling code here:
    }//GEN-LAST:event_btHqCadActionPerformed

    private void btHqDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHqDeleteActionPerformed
limparCampos();        // TODO add your handling code here:
    }//GEN-LAST:event_btHqDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btApaga;
    private javax.swing.JButton btAtualiza;
    private javax.swing.JButton btCadastro;
    private javax.swing.JButton btHqCad;
    private javax.swing.JButton btHqDelete;
    private javax.swing.JButton btHqProcurar;
    private javax.swing.JButton btHqUpdate;
    private javax.swing.JButton btProcura;
    private javax.swing.JPanel cadastroHq;
    private javax.swing.JPanel cadastroUsuario;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtCadastro;
    private javax.swing.JTextField txtEditora;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtQuadrinho;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
